addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.4.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.1")
addSbtPlugin("no.arktekk.sbt" % "aether-deploy" % "0.19.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.5")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "1.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.2.25")
