addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.3.2")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
addSbtPlugin("no.arktekk.sbt" % "aether-deploy" % "0.14")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "0.5.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.2.6")
